services:
  movie-fin:
    build: .
    environment:
      JELLYFIN_URL: ${JELLYFIN_URL:-http://192.168.1.170:8096}
      SEERR_URL: ${SEERR_URL:-http://192.168.1.170:5055}
    ports:
      - "8080:80"
    restart: unless-stopped
