services:
  movie-fin:
    build: .
    environment:
      JELLYFIN_URL: ${JELLYFIN_URL:-http://100.64.96.96:8096}
      SEERR_URL: ${SEERR_URL:-http://100.64.96.96:5055}
    ports:
      - "8080:80"
    restart: unless-stopped
